GOT TO CLEAN AND RESHAPE THE SEX COLUMN HAVING f,m,NaN (3 rows)

In [1]:
import pandas as pd
import os

In [4]:
pm_sex = pd.read_csv(r"../Cleaned amr data\Age_Clean_v2.csv")

In [6]:
#inspect the data
pm_sex['Sex'].value_counts(dropna=False)

Sex
f      3080
m      2646
NaN       3
Name: count, dtype: int64

In [7]:
#Standardize the gender
pm_sex['Sex'] = pm_sex['Sex'].replace({
    'f': 'F',
    'm': 'M'
})

In [9]:
#Verify the changes
pm_sex['Sex'].value_counts(dropna=False)

Sex
F      3080
M      2646
NaN       3
Name: count, dtype: int64

I need to fill the three NaN in the Sex Column, where two by names clue I got to know are male exept one

In [10]:
#look for columns
pm_sex.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Macro name', 'Country', 'Hospital Name',
       'Facility lebel', 'Origin', 'Identification number', 'Last name',
       'First name', 'Sex', 'Date of birth', 'Age', 'Age category',
       'Age_standardized', 'Age_years', 'Age_category', 'Ward', 'Institution',
       'Department', 'Location type', 'Date of admission', 'collection year',
       'Specimen number', 'Specimen date', 'Specimen type-Code',
       'Specimen type', 'Specimen type (Numeric)', 'Specimen Category',
       'Specimen Category Code', 'Reason', 'WHO-Pathogens', 'pathogen_species',
       'pathogen_genus', 'Gram Stain_Status', 'Organism type', 'Serotype',
       'Beta-lactamase', 'ESBL', 'Carbapenem resistance', 'MRSA',
       'Inducible clindamycin resistance', 'Date of data entry', 'Amikacin',
       'Amoxicillin/Clavulanic acid', 'Ampicillin', 'AZM', 'Cefazolin',
       'Cefepime', 'Cefixime', 'Cefotaxime', 'Cefoxitin', 'Ceftazidime',
       'Ceftriaxone', 'Chloramphenicol', 'Ciprofloxacin', 'Clindamycin',
       'Erythromycin', 'GEH', 'Gentamicin', 'Imipenem', 'Meropenem',
       'Nitrofurantoin', 'PEN', 'Piperacillin/Tazobactam', 'Tetracycline',
       'Trimethoprim/Sulfamethoxazole', 'VAN'],
      dtype='str')

In [13]:
#cut the names part
pm_sex.loc[
    pm_sex['Sex'].isna(),
    [
        'Sex',
        'First name',
        'Last name',
        'Identification number'
    ]
]

      Sex First name  Last name Identification number
1466  NaN        NaN        NaN                266717
3068  NaN     STELLA  ABRAHAMAN             M75-22-41
3909  NaN      AHMAD    SHABANI                 82062

In [14]:
#fill the 2 NaN
pm_sex.loc[3068, 'Sex'] = 'M'
pm_sex.loc[3909, 'Sex'] = 'M'

In [18]:
#Verify the changes
pm_sex.loc[
    pm_sex['Sex'].isna(),
    [
        'Sex',
        'First name',
        'Last name',
        'Identification number'
    ]
]

      Sex First name Last name Identification number
1466  NaN        NaN       NaN                266717

In [22]:
#save the cleaned data
#pm_sex.to_csv(r"../Cleaned amr data\Sex_with_na.csv", index=False)

I leave one row with NAN, use Mode Imputation to fill the 1 Nan

In [23]:
#mode
pm_sex['Sex'].mode()

0    F
Name: Sex, dtype: str

In [24]:
#fill with mode
pm_sex['Sex'] = pm_sex['Sex'].fillna(
    pm_sex['Sex'].mode()[0]
)

In [26]:
#verify the changes
pm_sex['Sex'].value_counts(dropna=False)

Sex
F    3081
M    2648
Name: count, dtype: int64

In [ ]:
#Save the cleaned data
#pm_sex.to_csv(r"../Cleaned amr data\Sex_Clean.csv", index=False)