In [1]:
import pandas as pd

In [2]:
pi = pd.read_excel("AMR DATA 7.7.2026.xlsx")

In [3]:
pi.head(5)

,Macro name,Country,Hospital Name,Facility lebel,Origin,Identification number,Last name,First name,Sex,Date of birth,...,GEH,Gentamicin,Imipenem,Meropenem,Nitrofurantoin,PEN,Piperacillin/Tazobactam,Tetracycline,Trimethoprim/Sulfamethoxazole,VAN
0,NaN,TZA,MZRH,Zonal hospital,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,TZA,MZRH,Zonal hospital,NaN,01 11 69 40,NaN,NaN,m,NaN,...,NaN,NaN,NaN,NaN,NaN,R,NaN,NaN,R,NaN
2,NaN,TZA,MZRH,Zonal hospital,NaN,1018535,NaN,NaN,m,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,TZA,MZRH,Zonal hospital,NaN,1103584,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,TZA,MZRH,Zonal hospital,NaN,1115940,NaN,NaN,f,NaN,...,NaN,18,NaN,29,25,NaN,NaN,NaN,6,NaN

In [4]:
pi['pathogen_species'].dropna().head(20)

200                  No growth
201    Acinetobacter baumannii
202    Acinetobacter baumannii
203    Acinetobacter baumannii
204    Acinetobacter baumannii
205    Acinetobacter baumannii
206    Acinetobacter baumannii
207    Acinetobacter baumannii
208    Acinetobacter baumannii
209    Acinetobacter baumannii
210    Acinetobacter baumannii
211    Acinetobacter baumannii
212    Acinetobacter baumannii
213    Acinetobacter baumannii
214    Acinetobacter baumannii
215    Acinetobacter baumannii
216    Acinetobacter baumannii
217    Acinetobacter baumannii
218    Acinetobacter baumannii
219    Acinetobacter baumannii
Name: pathogen_species, dtype: str

In [5]:
pi['pathogen_species'].dropna().sample(20, random_state=42)

13234      Staphylococcus, coagulase negative
24802                               No growth
45654                               No growth
44969                               No growth
17259                               No growth
16450             No significant growth found
45488                               No growth
12113      Staphylococcus, coagulase negative
27517                               No growth
43844                               No growth
17478                               No growth
25905                               No growth
25667                               No growth
6737     Klebsiella pneumoniae ss. pneumoniae
16233             No significant growth found
23303                               No growth
3052                         Escherichia coli
25875                               No growth
13735      Staphylococcus, coagulase negative
10787        Staphylococcus aureus ss. aureus
Name: pathogen_species, dtype: str

In [6]:
pi['pathogen_species'].value_counts(dropna=False)

pathogen_species
No growth                                      32204
Staphylococcus, coagulase negative              4372
Escherichia coli                                2361
Klebsiella pneumoniae ss. pneumoniae            1296
Staphylococcus aureus ss. aureus                1293
                                               ...
Streptococcus gallolyticus ss. pasteurianus        1
Serratia rubidaea                                  1
Streptococcus sanguinis                            1
Candidatus Xenohaliotis sp.                        1
Yersinia frederiksenii                             1
Name: count, Length: 131, dtype: int64

In [7]:
pi['pathogen_species'].unique()

<StringArray>
[                                            nan,
                                     'No growth',
                       'Acinetobacter baumannii',
 'Acinetobacter calcoaceticus-baumannii complex',
                             'Acinetobacter sp.',
                                'Aerococcus sp.',
                          'Aeromonas hydrophila',
                                 'Aeromonas sp.',
                         'Acinetobacter lwoffii',
                        'Arthroderma persicolor',
 ...
                      'Streptococcus salivarius',
                       'Streptococcus sanguinis',
                            'Staphylococcus sp.',
                             'Streptococcus sp.',
            'Streptococcus viridans, alpha-hem.',
                   'Candidatus Xenohaliotis sp.',
                            'No pathogens found',
                   'No significant growth found',
                                         'Yeast',
                        'Yersinia frederiksenii']
Length: 131, dtype: str

In [8]:
# Dataset size before filtering

pi.shape

(49302, 60)

In [9]:
# Check missing WHO-Pathogens

pi['WHO-Pathogens'].isnull().sum()

np.int64(43557)

Filter WHO-Pathogens

Reason:
The project team confirmed that rows with missing WHO-Pathogens also lack the required prediction labels. These records will not contribute to training the AMR prediction model, so they are excluded from the pathogen feature dataset.

In [10]:
# Keep only rows with WHO-Pathogens

pi_clean = pi[pi['WHO-Pathogens'].notna()].copy()

In [11]:
# Verify

pi_clean.shape

(5745, 60)

In [12]:
# Confirm no missing WHO-Pathogens remain

pi_clean['WHO-Pathogens'].isnull().sum()

np.int64(0)

In [13]:
# Inspect pathogen species

pi_clean['pathogen_species'].value_counts(dropna=False)

pathogen_species
Escherichia coli                                 2361
Klebsiella pneumoniae ss. pneumoniae             1296
Staphylococcus aureus ss. aureus                 1293
Acinetobacter baumannii                           534
Acinetobacter sp.                                 132
Escherichia sp.                                    68
Streptococcus pneumoniae                           21
Klebsiella pneumoniae ss. ozaenae                  10
NaN                                                 7
Salmonella sp.                                      6
Salmonella Typhi                                    5
Klebsiella pneumoniae ss. rhinoscleromatis          4
Salmonella Paratyphi A                              3
Acinetobacter lwoffii                               2
Acinetobacter calcoaceticus-baumannii complex       1
Acinetobacter radioresistens                        1
Escherichia vulneris                                1
Name: count, dtype: int64

In [14]:
pi_clean['pathogen_species'].unique()

<StringArray>
[                      'Acinetobacter baumannii',
 'Acinetobacter calcoaceticus-baumannii complex',
                             'Acinetobacter sp.',
                         'Acinetobacter lwoffii',
                  'Acinetobacter radioresistens',
                                             nan,
                              'Escherichia coli',
                               'Escherichia sp.',
                          'Escherichia vulneris',
             'Klebsiella pneumoniae ss. ozaenae',
          'Klebsiella pneumoniae ss. pneumoniae',
    'Klebsiella pneumoniae ss. rhinoscleromatis',
                        'Salmonella Paratyphi A',
                                'Salmonella sp.',
                              'Salmonella Typhi',
              'Staphylococcus aureus ss. aureus',
                      'Streptococcus pneumoniae']
Length: 17, dtype: str

In [15]:
pi_clean['pathogen_species'].value_counts()

pathogen_species
Escherichia coli                                 2361
Klebsiella pneumoniae ss. pneumoniae             1296
Staphylococcus aureus ss. aureus                 1293
Acinetobacter baumannii                           534
Acinetobacter sp.                                 132
Escherichia sp.                                    68
Streptococcus pneumoniae                           21
Klebsiella pneumoniae ss. ozaenae                  10
Salmonella sp.                                      6
Salmonella Typhi                                    5
Klebsiella pneumoniae ss. rhinoscleromatis          4
Salmonella Paratyphi A                              3
Acinetobacter lwoffii                               2
Acinetobacter calcoaceticus-baumannii complex       1
Acinetobacter radioresistens                        1
Escherichia vulneris                                1
Name: count, dtype: int64

In [16]:
pi_clean['pathogen_genus'] = pi_clean['pathogen_species'].str.split().str[0]

In [17]:
pi_clean[['pathogen_species', 'pathogen_genus']].head(15)

            pathogen_species pathogen_genus
201  Acinetobacter baumannii  Acinetobacter
202  Acinetobacter baumannii  Acinetobacter
203  Acinetobacter baumannii  Acinetobacter
204  Acinetobacter baumannii  Acinetobacter
205  Acinetobacter baumannii  Acinetobacter
206  Acinetobacter baumannii  Acinetobacter
207  Acinetobacter baumannii  Acinetobacter
208  Acinetobacter baumannii  Acinetobacter
209  Acinetobacter baumannii  Acinetobacter
210  Acinetobacter baumannii  Acinetobacter
211  Acinetobacter baumannii  Acinetobacter
212  Acinetobacter baumannii  Acinetobacter
213  Acinetobacter baumannii  Acinetobacter
214  Acinetobacter baumannii  Acinetobacter
215  Acinetobacter baumannii  Acinetobacter

In [18]:
pi_clean['pathogen_genus'].unique()

array(['Acinetobacter', nan, 'Escherichia', 'Klebsiella', 'Salmonella',
       'Staphylococcus', 'Streptococcus'], dtype=object)

In [19]:
pi_clean[
    pi_clean['pathogen_species'].isna()
]

,Macro name,Country,Hospital Name,Facility lebel,Origin,Identification number,Last name,First name,Sex,Date of birth,...,Gentamicin,Imipenem,Meropenem,Nitrofurantoin,PEN,Piperacillin/Tazobactam,Tetracycline,Trimethoprim/Sulfamethoxazole,VAN,pathogen_genus
1919,NaN,TZA,KCMC,Zonal hospital,h,269227,NaN,NaN,m,NaN,...,6,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN
15531,NaN,TZA,MNH,Zonal hospital,h,M74-77-96,KAMAGI,B/O FLORA,m,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15640,NaN,TZA,MNH,Zonal hospital,h,M79-99-92,MOKONGOTI,WARREN,m,NaN,...,NaN,NaN,NaN,NaN,6,NaN,NaN,25,NaN,NaN
15641,NaN,TZA,MNH,Zonal hospital,h,M80-59-19,UNKNOWN,JUMA,m,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15642,NaN,TZA,MNH,Zonal hospital,h,M81-12-55,MKERENGUFU,KURUTHUM,f,NaN,...,15,NaN,NaN,NaN,NaN,NaN,NaN,17,NaN,NaN
15643,NaN,TZA,MNH,Zonal hospital,h,M81-14-29,JOHN,JUMA,m,NaN,...,12,NaN,NaN,NaN,6,NaN,NaN,10,NaN,NaN
15644,NaN,TZA,MNH,Zonal hospital,h,M81-38-47,HARUNA,MUWAFAG,f,NaN,...,10,NaN,NaN,NaN,6,NaN,NaN,20,NaN,NaN

In [20]:
pi_clean[
    pi_clean['pathogen_species'].isna()
][['WHO-Pathogens', 'pathogen_species']]

      WHO-Pathogens pathogen_species
1919             cn              NaN
15531            sh              NaN
15640           snc              NaN
15641           snc              NaN
15642           snc              NaN
15643           snc              NaN
15644           snc              NaN

Go back again to clean the dataframe for the one having variables in WHO-Pathogens but pathogen_species are nan since ahedad also they dont have labled.

In [21]:
# Keep only rows with Pathogens species

pi_psclean = pi_clean[pi_clean['pathogen_species'].notna()].copy()

In [22]:
pi_psclean.shape

(5738, 61)

In [23]:
pi_psclean['pathogen_species'].isnull().sum()

np.int64(0)

In [24]:
pi_psclean['pathogen_species'].value_counts(dropna=False)

pathogen_species
Escherichia coli                                 2361
Klebsiella pneumoniae ss. pneumoniae             1296
Staphylococcus aureus ss. aureus                 1293
Acinetobacter baumannii                           534
Acinetobacter sp.                                 132
Escherichia sp.                                    68
Streptococcus pneumoniae                           21
Klebsiella pneumoniae ss. ozaenae                  10
Salmonella sp.                                      6
Salmonella Typhi                                    5
Klebsiella pneumoniae ss. rhinoscleromatis          4
Salmonella Paratyphi A                              3
Acinetobacter lwoffii                               2
Acinetobacter calcoaceticus-baumannii complex       1
Acinetobacter radioresistens                        1
Escherichia vulneris                                1
Name: count, dtype: int64

In [25]:
pi_psclean['pathogen_species'].unique()

<StringArray>
[                      'Acinetobacter baumannii',
 'Acinetobacter calcoaceticus-baumannii complex',
                             'Acinetobacter sp.',
                         'Acinetobacter lwoffii',
                  'Acinetobacter radioresistens',
                              'Escherichia coli',
                               'Escherichia sp.',
                          'Escherichia vulneris',
             'Klebsiella pneumoniae ss. ozaenae',
          'Klebsiella pneumoniae ss. pneumoniae',
    'Klebsiella pneumoniae ss. rhinoscleromatis',
                        'Salmonella Paratyphi A',
                                'Salmonella sp.',
                              'Salmonella Typhi',
              'Staphylococcus aureus ss. aureus',
                      'Streptococcus pneumoniae']
Length: 16, dtype: str

In [26]:
pi_psclean[['WHO-Pathogens', 'pathogen_species', 'pathogen_genus']]

                  WHO-Pathogens          pathogen_species pathogen_genus
201           Acinetobacter sp.   Acinetobacter baumannii  Acinetobacter
202           Acinetobacter sp.   Acinetobacter baumannii  Acinetobacter
203           Acinetobacter sp.   Acinetobacter baumannii  Acinetobacter
204           Acinetobacter sp.   Acinetobacter baumannii  Acinetobacter
205           Acinetobacter sp.   Acinetobacter baumannii  Acinetobacter
...                         ...                       ...            ...
15705  Streptococcus pneumoniae  Streptococcus pneumoniae  Streptococcus
15706  Streptococcus pneumoniae  Streptococcus pneumoniae  Streptococcus
15707  Streptococcus pneumoniae  Streptococcus pneumoniae  Streptococcus
15708  Streptococcus pneumoniae  Streptococcus pneumoniae  Streptococcus
15709  Streptococcus pneumoniae  Streptococcus pneumoniae  Streptococcus

[5738 rows x 3 columns]

In [27]:
pi_psclean['Gram Stain_Status'].unique()

<StringArray>
['Gram Negative bacterial', 'Gram Positive bacteria']
Length: 2, dtype: str

In [28]:
pi_psclean['Gram Stain_Status'].isna().sum()

np.int64(0)

In [29]:
pi_psclean.info()

<class 'pandas.DataFrame'>
Index: 5738 entries, 201 to 15709
Data columns (total 61 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Macro name                        0 non-null      float64
 1   Country                           5738 non-null   str
 2   Hospital Name                     5738 non-null   str
 3   Facility lebel                    5738 non-null   str
 4   Origin                            3748 non-null   str
 5   Identification number             5735 non-null   object
 6   Last name                         1608 non-null   object
 7   First name                        1607 non-null   object
 8   Sex                               5735 non-null   object
 9   Date of birth                     3 non-null      object
 10  Age                               5725 non-null   object
 11  Age category                      5678 non-null   object
 12  Ward                              5736 non-null   object
 13  Institution                       5299 non-null   object
 14  Department                        5737 non-null   str
 15  Location type                     5737 non-null   str
 16  Date of admission                 2501 non-null   object
 17  collection year                   5738 non-null   float64
 18  Specimen number                   5732 non-null   object
 19  Specimen date                     5734 non-null   object
 20  Specimen type-Code                5735 non-null   object
 21  Specimen type                     5731 non-null   str
 22  Specimen type (Numeric)           5735 non-null   float64
 23  Reason                            5738 non-null   str
 24  WHO-Pathogens                     5738 non-null   str
 25  pathogen_species                  5738 non-null   str
 26  Gram Stain_Status                 5738 non-null   str
 27  Organism type                     5738 non-null   str
 28  Serotype                          14 non-null     object
 29  Beta-lactamase                    1 non-null      str
 30  ESBL                              2903 non-null   str
 31  Carbapenem resistance             214 non-null    object
 32  MRSA                              408 non-null    str
 33  Inducible clindamycin resistance  575 non-null    str
 34  Date of data entry                5431 non-null   object
 35  Amikacin                          3766 non-null   object
 36  Amoxicillin/Clavulanic acid       3244 non-null   object
 37  Ampicillin                        2564 non-null   object
 38  AZM                               237 non-null    object
 39  Cefazolin                         242 non-null    object
 40  Cefepime                          3398 non-null   object
 41  Cefixime                          153 non-null    object
 42  Cefotaxime                        1400 non-null   object
 43  Cefoxitin                         1563 non-null   object
 44  Ceftazidime                       4087 non-null   object
 45  Ceftriaxone                       3594 non-null   object
 46  Chloramphenicol                   934 non-null    object
 47  Ciprofloxacin                     4078 non-null   object
 48  Clindamycin                       1061 non-null   object
 49  Erythromycin                      940 non-null    object
 50  GEH                               1 non-null      float64
 51  Gentamicin                        4651 non-null   object
 52  Imipenem                          571 non-null    object
 53  Meropenem                         3928 non-null   object
 54  Nitrofurantoin                    2753 non-null   object
 55  PEN                               354 non-null    object
 56  Piperacillin/Tazobactam           3217 non-null   object
 57  Tetracycline                      833 non-null    object
 58  Trimethoprim/Sulfamethoxazole     3756 non-null   object
 59  VAN                               177 non-null    object
 60  pathogen_genus                    5738 non-null   object
dtypes: float64(4), object(41), str(16)
memory usage: 2.7+ MB

In [30]:
pi_psclean['WHO-Pathogens'].unique()

<StringArray>
[                   'Acinetobacter sp.',
                     'Escherichia coli',
 'Klebsiella pneumoniae ss. pneumoniae',
                       'Salmonella sp.',
     'Staphylococcus aureus ss. aureus',
             'Streptococcus pneumoniae']
Length: 6, dtype: str

In [31]:
pi_psclean['pathogen_genus'].unique()

array(['Acinetobacter', 'Escherichia', 'Klebsiella', 'Salmonella',
       'Staphylococcus', 'Streptococcus'], dtype=object)

In [32]:
pi_psclean['pathogen_species'].unique()

<StringArray>
[                      'Acinetobacter baumannii',
 'Acinetobacter calcoaceticus-baumannii complex',
                             'Acinetobacter sp.',
                         'Acinetobacter lwoffii',
                  'Acinetobacter radioresistens',
                              'Escherichia coli',
                               'Escherichia sp.',
                          'Escherichia vulneris',
             'Klebsiella pneumoniae ss. ozaenae',
          'Klebsiella pneumoniae ss. pneumoniae',
    'Klebsiella pneumoniae ss. rhinoscleromatis',
                        'Salmonella Paratyphi A',
                                'Salmonella sp.',
                              'Salmonella Typhi',
              'Staphylococcus aureus ss. aureus',
                      'Streptococcus pneumoniae']
Length: 16, dtype: str

In [34]:
#pi_psclean.to_csv("pathogen_information_clean.csv", index=False)

concern sepecimen information they use specimen type, [ still not sure concern [specimen category], in which in specimen type they use only[blood] [urine] [pus] ]

In [35]:
pi_psclean['Specimen type'].unique()

<StringArray>
['urine', 'Blood', 'Pus', nan]
Length: 4, dtype: str

In [36]:
pi_psclean['Specimen type'].value_counts(dropna=False)

Specimen type
urine    3062
Blood    1983
Pus       686
NaN         7
Name: count, dtype: int64

In [37]:
pi_psclean[
    pi_psclean['Specimen type'].isna()
][['WHO-Pathogens', 'pathogen_species', 'Specimen type']]

,WHO-Pathogens,pathogen_species,Specimen type
772,Acinetobacter sp.,Acinetobacter sp.,NaN
2871,Escherichia coli,Escherichia coli,NaN
3244,Escherichia coli,Escherichia coli,NaN
9625,Salmonella sp.,Salmonella sp.,NaN
9768,Staphylococcus aureus ss. aureus,Staphylococcus aureus ss. aureus,NaN
10634,Staphylococcus aureus ss. aureus,Staphylococcus aureus ss. aureus,NaN
10779,Staphylococcus aureus ss. aureus,Staphylococcus aureus ss. aureus,NaN

Edit column manually to shift to close place with other pathogen informations in pathogen_information_clean.csv file

then go to run again the specimen information notebook file.