Age - Clean blank datas [13] and standardize the variables in here if is x Days/ x Months / x Years, age category = New Born, Pediatric, Adults. [to do reaserch on this age division]
and to search litreture view on the weight of this age input in this model and also to see how to categories these ages according to WHO standard, and also compare with reality to our location and ask discuss with mentors from this project

Sex clean no blank when age are done cleaned, but got to standardize them, but actually are alreadyy in f and m, but can follow standard on how to put he gender variable

location type is inpatient_outpatient will be clean

ward_departmnet - standardize the naming of variables.

In [38]:
import pandas as pd

In [39]:
pm_age = pd.read_csv("specimen_information_clean_6.csv")

In [40]:
#Inspect age
pm_age['Age'].value_counts(dropna=False)

Age
1d     227
1      200
2      140
60     105
3       93
      ...
98       1
100      1
33d      1
45d      1
29d      1
Name: count, Length: 152, dtype: int64

In [41]:
pm_age['Age'].sample(50, random_state=42)

3562     90
4119     54
4482     41
4211      1
5604     46
561      22
4176      4
4216      5
5597     72
177       2
1109      2
3379     2d
401      23
3014      4
4195     47
1033     68
2164     69
3437     42
3491     3d
453      57
80       36
1965     30
4334    11d
3290     91
5152      3
3318     68
1397     27
4920    14d
3082     52
696      60
5263     76
2754     55
4295     3m
969      59
848     101
5661     65
101      51
4915     28
4310     69
611      1d
751      61
5325     81
333       1
319      19
2629     54
1181     28
1129     77
1411     60
3268     72
712      54
Name: Age, dtype: str

In [42]:
pm_age['Age'].isna().sum()

np.int64(13)

In [43]:
pm_age['Age'].unique()

<StringArray>
[ '31',   '3',  '15',  '47',   '1',  '56',  '18',   '8',  '1m', '12d',
 ...
  '96', '17d', '10f', '23d', '18m',  '98', '100', '33d', '45d', '29d']
Length: 152, dtype: str

DOING RAW CHECK ON AGES  OUT OF CODES

In [44]:
#start from
#pm_age.to_csv("age_raw.csv", index=False)

DONE MANUAL EDIT OF DATA

In [45]:
pm_age=pd.read_csv("age_raw.csv")

In [46]:
pm_age['Age'].unique()

<StringArray>
[ '31',   '3',  '15',  '47',   '1',  '56',  '18',   '8',  '1m', '12d',
 ...
 '51d',  '96', '17d', '23d', '18m',  '98', '100', '33d', '45d', '29d']
Length: 150, dtype: str

In [47]:
#function to standardize
def standardize_age(age):
    if pd.isna(age):
        return None
    
    age = str(age).strip().lower()
    
    # Days
    if age.endswith('d'):
        value = age.replace('d', '')
        return f"{value} Days"
    
    # Months
    elif age.endswith('m'):
        value = age.replace('m', '')
        return f"{value} Months"
    
    # Years (no letter)
    else:
        return f"{age} Years"

In [48]:
pm_age['Age_standardized'] = pm_age['Age'].apply(standardize_age)

In [49]:
pm_age[['Age', 'Age_standardized']].sample(20, random_state=42)

     Age Age_standardized
3562  90         90 Years
4119  54         54 Years
4482  41         41 Years
4211   1          1 Years
5604  46         46 Years
561   22         22 Years
4176   4          4 Years
4216   5          5 Years
5597  72         72 Years
177    2          2 Years
1109   2          2 Years
3379  2d           2 Days
401   23         23 Years
3014   4          4 Years
4195  47         47 Years
1033  68         68 Years
2164  69         69 Years
3437  42         42 Years
3491  3d           3 Days
453   57         57 Years

In [50]:
pm_age['Age_standardized'].unique()

<StringArray>
[ '31 Years',   '3 Years',  '15 Years',  '47 Years',   '1 Years',  '56 Years',
  '18 Years',   '8 Years',  '1 Months',   '12 Days',
 ...
   '51 Days',  '96 Years',   '17 Days',   '23 Days', '18 Months',  '98 Years',
 '100 Years',   '33 Days',   '45 Days',   '29 Days']
Length: 150, dtype: str

convert the age for easy machine language approach as 
12 Days     → 0.03 years
18 Months   → 1.5 years
31 Years    → 31 years

here workflow as;
- Keep the original raw Age column (for traceability)
- Create a standardized readable age column (Age_standardized)
- Create a numeric age column in years (Age_years) for analysis/modeling
- Create the age category based on your team's classification

In [51]:
#function to convert to numeric
def age_to_years(age):
    if pd.isna(age):
        return None
    
    age = str(age).strip().lower()
    
    if age.endswith('d'):
        value = float(age.replace('d',''))
        return value / 365
    
    elif age.endswith('m'):
        value = float(age.replace('m',''))
        return value / 12
    
    else:
        return float(age)

In [52]:
pm_age['Age_years'] = pm_age['Age'].apply(age_to_years)

In [53]:
pm_age[['Age', 'Age_standardized', 'Age_years']].sample(20, random_state=42)

     Age Age_standardized  Age_years
3562  90         90 Years  90.000000
4119  54         54 Years  54.000000
4482  41         41 Years  41.000000
4211   1          1 Years   1.000000
5604  46         46 Years  46.000000
561   22         22 Years  22.000000
4176   4          4 Years   4.000000
4216   5          5 Years   5.000000
5597  72         72 Years  72.000000
177    2          2 Years   2.000000
1109   2          2 Years   2.000000
3379  2d           2 Days   0.005479
401   23         23 Years  23.000000
3014   4          4 Years   4.000000
4195  47         47 Years  47.000000
1033  68         68 Years  68.000000
2164  69         69 Years  69.000000
3437  42         42 Years  42.000000
3491  3d           3 Days   0.008219
453   57         57 Years  57.000000

CREATING THE NEW AGE CATEGORY

In [54]:
#fxn for age categorizing
def age_category(age):
    if pd.isna(age):
        return None
    
    if age <= 1:
        return "Infant"
    
    elif age <= 9:
        return "Children"
    
    elif age <= 19:
        return "Adolescents"
    
    elif age <= 34:
        return "Youth"
    
    elif age <= 44:
        return "Young adults"
    
    elif age <= 59:
        return "Middle age"
    
    else:
        return "Elderly"

In [55]:
pm_age['Age_category'] = pm_age['Age_years'].apply(age_category)

In [56]:
#inspect
pm_age['Age_category'].value_counts(dropna=False)

Age_category
Elderly         1631
Infant          1067
Middle age       854
Youth            821
Young adults     534
Children         503
Adolescents      306
NaN               13
Name: count, dtype: int64

In [57]:
pm_age['Age_years'].describe()

count    5716.000000
mean       37.125098
std        28.230510
min         0.000000
25%         5.000000
50%        37.000000
75%        62.000000
max       121.000000
Name: Age_years, dtype: float64

In [58]:
pm_age[['Age', 'Age_standardized', 'Age_years', 'Age category', 'Age_category']]

     Age Age_standardized  Age_years Age category Age_category
0     31         31 Years  31.000000          adu        Youth
1      3          3 Years   3.000000          ped     Children
2     15         15 Years  15.000000          ped  Adolescents
3     47         47 Years  47.000000          adu   Middle age
4      1          1 Years   1.000000          ped       Infant
...   ..              ...        ...          ...          ...
5724  2m         2 Months   0.166667          ped       Infant
5725   7          7 Years   7.000000          ped     Children
5726  3d           3 Days   0.008219          new       Infant
5727  24         24 Years  24.000000          adu        Youth
5728  1m         1 Months   0.083333          ped       Infant

[5729 rows x 5 columns]

CHANGE POSITION OF COLUMNS

In [59]:
age_cat_position = pm_age.columns.get_loc('Age category')

In [60]:
age_standardized = pm_age.pop('Age_standardized')
age_years = pm_age.pop('Age_years')
age_category = pm_age.pop('Age_category')

pm_age.insert(age_cat_position + 1, 'Age_standardized', age_standardized)
pm_age.insert(age_cat_position + 2, 'Age_years', age_years)
pm_age.insert(age_cat_position + 3, 'Age_category', age_category)

In [61]:
pm_age.columns

Index(['Macro name', 'Country', 'Hospital Name', 'Facility lebel', 'Origin',
       'Identification number', 'Last name', 'First name', 'Sex',
       'Date of birth', 'Age', 'Age category', 'Age_standardized', 'Age_years',
       'Age_category', 'Ward', 'Institution', 'Department', 'Location type',
       'Date of admission', 'collection year', 'Specimen number',
       'Specimen date', 'Specimen type-Code', 'Specimen type',
       'Specimen type (Numeric)', 'Specimen Category',
       'Specimen Category Code', 'Reason', 'WHO-Pathogens', 'pathogen_species',
       'pathogen_genus', 'Gram Stain_Status', 'Organism type', 'Serotype',
       'Beta-lactamase', 'ESBL', 'Carbapenem resistance', 'MRSA',
       'Inducible clindamycin resistance', 'Date of data entry', 'Amikacin',
       'Amoxicillin/Clavulanic acid', 'Ampicillin', 'AZM', 'Cefazolin',
       'Cefepime', 'Cefixime', 'Cefotaxime', 'Cefoxitin', 'Ceftazidime',
       'Ceftriaxone', 'Chloramphenicol', 'Ciprofloxacin', 'Clindamycin',
       'Erythromycin', 'GEH', 'Gentamicin', 'Imipenem', 'Meropenem',
       'Nitrofurantoin', 'PEN', 'Piperacillin/Tazobactam', 'Tetracycline',
       'Trimethoprim/Sulfamethoxazole', 'VAN'],
      dtype='str')

In [62]:
#pm_age.to_csv("Age_clean_v1.csv")

checking if i can use ward to assit fill on the 13 blanks

In [63]:
pm_age['Ward'].unique()

<StringArray>
[        'BIMA',         'POPD',         'MOPD',         'nicu',
          'icu',         'mopd',         'popd',          'ngw',
          'uro',           'm2',
 ...
          'nec', 'BAYLOR UNITY',        'WD 05',           'DM',
         'DIAB',         'MHDU',          'EYE',          'WD4',
        'WD 06',          'phe']
Length: 164, dtype: str

In [69]:
pm_age_na = pm_age[pm_age['Age'].isna()].copy()

In [71]:
pm_age_na['Age']

103     NaN
535     NaN
563     NaN
1436    NaN
3385    NaN
3516    NaN
4426    NaN
4819    NaN
4878    NaN
4936    NaN
5058    NaN
5101    NaN
5120    NaN
Name: Age, dtype: str

In [72]:
pm_age_na

,Macro name,Country,Hospital Name,Facility lebel,Origin,Identification number,Last name,First name,Sex,Date of birth,...,GEH,Gentamicin,Imipenem,Meropenem,Nitrofurantoin,PEN,Piperacillin/Tazobactam,Tetracycline,Trimethoprim/Sulfamethoxazole,VAN
103,NaN,TZA,KCMC,Zonal hospital,h,234524,NaN,NaN,m,NaN,...,NaN,Susceptible,NaN,Susceptible,6,NaN,Susceptible,NaN,Intermediate,NaN
535,NaN,TZA,MZRH,Zonal hospital,NaN,01 13 18 41,NaN,NaN,f,NaN,...,NaN,Resistant,NaN,Susceptible,NaN,NaN,Susceptible,NaN,Susceptible,NaN
563,NaN,TZA,KCMC,Zonal hospital,h,278498,NaN,NaN,m,NaN,...,NaN,Resistant,NaN,NaN,NaN,NaN,NaN,NaN,Susceptible,NaN
1436,NaN,TZA,KCMC,Zonal hospital,h,261919,NaN,NaN,f,NaN,...,NaN,Susceptible,NaN,Susceptible,NaN,NaN,Susceptible,NaN,NaN,NaN
3385,NaN,TZA,KCMC,Zonal hospital,h,247002,NaN,NaN,m,NaN,...,NaN,Susceptible,NaN,Susceptible,Susceptible,NaN,Susceptible,NaN,Resistant,NaN
3516,NaN,TZA,KCMC,Zonal hospital,h,278199,NaN,NaN,f,NaN,...,NaN,NaN,NaN,Susceptible,NaN,NaN,Susceptible,NaN,Resistant,NaN
4426,NaN,TZA,MZRH,Zonal hospital,NaN,01 12 88 45,NaN,NaN,m,NaN,...,NaN,Resistant,NaN,NaN,NaN,R,NaN,NaN,Resistant,NaN
4819,NaN,TZA,KCMC,Zonal hospital,h,235004,NaN,NaN,f,NaN,...,NaN,Susceptible,NaN,NaN,NaN,NaN,NaN,NaN,Susceptible,NaN
4878,NaN,TZA,KCMC,Zonal hospital,h,240934,NaN,NaN,m,NaN,...,NaN,Resistant,NaN,NaN,NaN,NaN,NaN,NaN,Resistant,18
4936,NaN,TZA,KCMC,Zonal hospital,h,247539,NaN,NaN,m,NaN,...,NaN,Resistant,NaN,NaN,NaN,NaN,NaN,NaN,Resistant,NaN
5058,NaN,TZA,KCMC,Zonal hospital,h,264197,NaN,NaN,f,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5101,NaN,TZA,KCMC,Zonal hospital,h,273175,NaN,NaN,f,NaN,...,NaN,Resistant,NaN,NaN,NaN,NaN,NaN,NaN,Resistant,NaN
5120,NaN,TZA,KCMC,Zonal hospital,h,278197,NaN,NaN,f,NaN,...,NaN,Intermediate,NaN,NaN,NaN,NaN,NaN,Resistant,Resistant,NaN

In [73]:
pm_age_na['Ward'].unique()

<StringArray>
['EMD', 'nicu', 'P2', 'OPD', 'S1', 'POPD', 'M2', 'MICU', 'HUD', 'BURN', 'P3']
Length: 11, dtype: str

In [74]:
pm_age_na['Age category'].unique()

<StringArray>
[nan, 'ped']
Length: 2, dtype: str

In [76]:
pm_age_na['Institution'].unique()

<StringArray>
['2', 'MZRH_03', nan]
Length: 3, dtype: str

In [77]:
pm_age_na['Department'].unique()

<StringArray>
['eme', 'icu', 'ped', 'MED', 'sur', 'med', 'burn']
Length: 7, dtype: str

In [78]:
#create csv to fill blank or clean blanks!
pm_age.to_csv("Age_clean_v1_blank.csv")