CLEAN THE SPECIMEN INFORMATION

In [1]:
import pandas as pd

In [2]:
sp = pd.read_csv("pathogen_information_clean.csv")

In [3]:
sp[
    sp['Specimen type'].isna()
][['WHO-Pathogens', 'pathogen_species', 'Specimen type']]

,WHO-Pathogens,pathogen_species,Specimen type
571,Acinetobacter sp.,Acinetobacter sp.,NaN
935,Escherichia coli,Escherichia coli,NaN
1308,Escherichia coli,Escherichia coli,NaN
4415,Salmonella sp.,Salmonella sp.,NaN
4538,Staphylococcus aureus ss. aureus,Staphylococcus aureus ss. aureus,NaN
5404,Staphylococcus aureus ss. aureus,Staphylococcus aureus ss. aureus,NaN
5549,Staphylococcus aureus ss. aureus,Staphylococcus aureus ss. aureus,NaN

In [4]:
sp['Specimen type'].value_counts(dropna=False)

Specimen type
urine    3062
Blood    1983
Pus       686
NaN         7
Name: count, dtype: int64

CLEAN THE NAN FROM THE SPECIMEN COLUMN MAKING NEW DATAFRAME.

In [5]:
#clean NAN from specimen
sp_clean = sp[sp['Specimen type'].notna()].copy()

In [6]:
sp_clean['Specimen type'].value_counts(dropna=False)

Specimen type
urine    3062
Blood    1983
Pus       686
Name: count, dtype: int64

In [7]:
sp_clean['Reason'].isna().sum()

np.int64(0)

SAVING THE FILE AFTER CLEAN SPECIMEN INFORMATION

In [8]:

#sp_clean.to_csv("specimen_information_clean.csv", index = False)

confirm the columns arrangement

In [9]:
sp_clean.columns

Index(['Macro name', 'Country', 'Hospital Name', 'Facility lebel', 'Origin',
       'Identification number', 'Last name', 'First name', 'Sex',
       'Date of birth', 'Age', 'Age category', 'Ward', 'Institution',
       'Department', 'Location type', 'Date of admission', 'collection year',
       'Specimen number', 'Specimen date', 'Specimen type-Code',
       'Specimen type', 'Specimen type (Numeric)', 'Reason', 'WHO-Pathogens',
       'pathogen_species', 'pathogen_genus', 'Gram Stain_Status',
       'Organism type', 'Serotype', 'Beta-lactamase', 'ESBL',
       'Carbapenem resistance', 'MRSA', 'Inducible clindamycin resistance',
       'Date of data entry', 'Amikacin', 'Amoxicillin/Clavulanic acid',
       'Ampicillin', 'AZM', 'Cefazolin', 'Cefepime', 'Cefixime', 'Cefotaxime',
       'Cefoxitin', 'Ceftazidime', 'Ceftriaxone', 'Chloramphenicol',
       'Ciprofloxacin', 'Clindamycin', 'Erythromycin', 'GEH', 'Gentamicin',
       'Imipenem', 'Meropenem', 'Nitrofurantoin', 'PEN',
       'Piperacillin/Tazobactam', 'Tetracycline',
       'Trimethoprim/Sulfamethoxazole', 'VAN'],
      dtype='str')

THERE IS RESERCHER DECISION ON 'SPECIMEN CATEGORY' INPUT, WHERE HERE I GOT TO CREATE NEW COLUMN FOR THIS ACCORDING TO [ URINE = UTI [Urinary Tract Infection] , BLOOD = BSI [Blood Stream Infection ], PUS = SSTI [Skin and Soft Tissue Infection]]

In [10]:
sp_clean['Specimen type'].unique()

<StringArray>
['urine', 'Blood', 'Pus']
Length: 3, dtype: str

In [11]:
#create dictionary first
specimen_category = {
    'urine': 'Urinary Tract Infection',
    'Blood': 'Blood Stream Infection',
    'Pus': 'Skin and Soft Tissue Infection'
}

In [12]:
#create new column
sp_clean['Specimen Category'] = (
    sp_clean['Specimen type']
        .map(specimen_category)
)

In [13]:
sp_clean['Specimen Category'].unique()
#sp_clean['Specimen Category']

<StringArray>
[       'Urinary Tract Infection',         'Blood Stream Infection',
 'Skin and Soft Tissue Infection']
Length: 3, dtype: str

In [14]:
sp_clean.columns

Index(['Macro name', 'Country', 'Hospital Name', 'Facility lebel', 'Origin',
       'Identification number', 'Last name', 'First name', 'Sex',
       'Date of birth', 'Age', 'Age category', 'Ward', 'Institution',
       'Department', 'Location type', 'Date of admission', 'collection year',
       'Specimen number', 'Specimen date', 'Specimen type-Code',
       'Specimen type', 'Specimen type (Numeric)', 'Reason', 'WHO-Pathogens',
       'pathogen_species', 'pathogen_genus', 'Gram Stain_Status',
       'Organism type', 'Serotype', 'Beta-lactamase', 'ESBL',
       'Carbapenem resistance', 'MRSA', 'Inducible clindamycin resistance',
       'Date of data entry', 'Amikacin', 'Amoxicillin/Clavulanic acid',
       'Ampicillin', 'AZM', 'Cefazolin', 'Cefepime', 'Cefixime', 'Cefotaxime',
       'Cefoxitin', 'Ceftazidime', 'Ceftriaxone', 'Chloramphenicol',
       'Ciprofloxacin', 'Clindamycin', 'Erythromycin', 'GEH', 'Gentamicin',
       'Imipenem', 'Meropenem', 'Nitrofurantoin', 'PEN',
       'Piperacillin/Tazobactam', 'Tetracycline',
       'Trimethoprim/Sulfamethoxazole', 'VAN', 'Specimen Category'],
      dtype='str')

In [15]:
#create dictionary for specimen code
category_code = {
    'urine':'UTI',
    'Blood':'BSI',
    'Pus':'SSTI'
}

In [16]:
sp_clean['Specimen Category Code'] = (
    sp_clean['Specimen type']
        .map(category_code)
)

In [17]:
sp_clean['Specimen Category Code'].unique()

<StringArray>
['UTI', 'BSI', 'SSTI']
Length: 3, dtype: str

In [18]:
# arrange the column near to specimen information group, but check first wher are they
sp_clean.columns.tolist()

['Macro name',
 'Country',
 'Hospital Name',
 'Facility lebel',
 'Origin',
 'Identification number',
 'Last name',
 'First name',
 'Sex',
 'Date of birth',
 'Age',
 'Age category',
 'Ward',
 'Institution',
 'Department',
 'Location type',
 'Date of admission',
 'collection year',
 'Specimen number',
 'Specimen date',
 'Specimen type-Code',
 'Specimen type',
 'Specimen type (Numeric)',
 'Reason',
 'WHO-Pathogens',
 'pathogen_species',
 'pathogen_genus',
 'Gram Stain_Status',
 'Organism type',
 'Serotype',
 'Beta-lactamase',
 'ESBL',
 'Carbapenem resistance',
 'MRSA',
 'Inducible clindamycin resistance',
 'Date of data entry',
 'Amikacin',
 'Amoxicillin/Clavulanic acid',
 'Ampicillin',
 'AZM',
 'Cefazolin',
 'Cefepime',
 'Cefixime',
 'Cefotaxime',
 'Cefoxitin',
 'Ceftazidime',
 'Ceftriaxone',
 'Chloramphenicol',
 'Ciprofloxacin',
 'Clindamycin',
 'Erythromycin',
 'GEH',
 'Gentamicin',
 'Imipenem',
 'Meropenem',
 'Nitrofurantoin',
 'PEN',
 'Piperacillin/Tazobactam',
 'Tetracycline',
 'Trimethoprim/Sulfamethoxazole',
 'VAN',
 'Specimen Category',
 'Specimen Category Code']

now shifting the postion of new columns, to near other specimen information

In [19]:
#create pop data
sc = sp_clean.pop('Specimen Category')

In [20]:
#create first position
position_sc = sp_clean.columns.get_loc('Specimen type (Numeric)') + 1

In [21]:
#moving the column
sp_clean.insert(position_sc, 'Specimen Category', sc)

In [22]:
#check
sp_clean.columns

Index(['Macro name', 'Country', 'Hospital Name', 'Facility lebel', 'Origin',
       'Identification number', 'Last name', 'First name', 'Sex',
       'Date of birth', 'Age', 'Age category', 'Ward', 'Institution',
       'Department', 'Location type', 'Date of admission', 'collection year',
       'Specimen number', 'Specimen date', 'Specimen type-Code',
       'Specimen type', 'Specimen type (Numeric)', 'Specimen Category',
       'Reason', 'WHO-Pathogens', 'pathogen_species', 'pathogen_genus',
       'Gram Stain_Status', 'Organism type', 'Serotype', 'Beta-lactamase',
       'ESBL', 'Carbapenem resistance', 'MRSA',
       'Inducible clindamycin resistance', 'Date of data entry', 'Amikacin',
       'Amoxicillin/Clavulanic acid', 'Ampicillin', 'AZM', 'Cefazolin',
       'Cefepime', 'Cefixime', 'Cefotaxime', 'Cefoxitin', 'Ceftazidime',
       'Ceftriaxone', 'Chloramphenicol', 'Ciprofloxacin', 'Clindamycin',
       'Erythromycin', 'GEH', 'Gentamicin', 'Imipenem', 'Meropenem',
       'Nitrofurantoin', 'PEN', 'Piperacillin/Tazobactam', 'Tetracycline',
       'Trimethoprim/Sulfamethoxazole', 'VAN', 'Specimen Category Code'],
      dtype='str')

In [23]:
#moving on to moving the specimnen category code
#create pop for value exist already
scc = sp_clean.pop('Specimen Category Code')

In [24]:
#position
position_scc = sp_clean.columns.get_loc('Specimen Category') + 1

In [25]:
#moving
sp_clean.insert(position_scc, 'Specimen Category Code', scc)

In [26]:
#check 
sp_clean.columns.tolist()

['Macro name',
 'Country',
 'Hospital Name',
 'Facility lebel',
 'Origin',
 'Identification number',
 'Last name',
 'First name',
 'Sex',
 'Date of birth',
 'Age',
 'Age category',
 'Ward',
 'Institution',
 'Department',
 'Location type',
 'Date of admission',
 'collection year',
 'Specimen number',
 'Specimen date',
 'Specimen type-Code',
 'Specimen type',
 'Specimen type (Numeric)',
 'Specimen Category',
 'Specimen Category Code',
 'Reason',
 'WHO-Pathogens',
 'pathogen_species',
 'pathogen_genus',
 'Gram Stain_Status',
 'Organism type',
 'Serotype',
 'Beta-lactamase',
 'ESBL',
 'Carbapenem resistance',
 'MRSA',
 'Inducible clindamycin resistance',
 'Date of data entry',
 'Amikacin',
 'Amoxicillin/Clavulanic acid',
 'Ampicillin',
 'AZM',
 'Cefazolin',
 'Cefepime',
 'Cefixime',
 'Cefotaxime',
 'Cefoxitin',
 'Ceftazidime',
 'Ceftriaxone',
 'Chloramphenicol',
 'Ciprofloxacin',
 'Clindamycin',
 'Erythromycin',
 'GEH',
 'Gentamicin',
 'Imipenem',
 'Meropenem',
 'Nitrofurantoin',
 'PEN',
 'Piperacillin/Tazobactam',
 'Tetracycline',
 'Trimethoprim/Sulfamethoxazole',
 'VAN']

In [27]:
#sp_clean.to_csv("specimen_information_clean_2.csv", index = False)

NEED TO STANDADIZE THE VARIBLE, beacuse we got urine, Blood, Pus. need to standardize the Urine

In [28]:
#to standardize 
sp_clean['Specimen type'] = sp_clean['Specimen type'].str.title()

In [29]:
sp_clean['Specimen type'].unique()

<StringArray>
['Urine', 'Blood', 'Pus']
Length: 3, dtype: str

In [30]:
#sp_clean.to_csv("specimen_information_clean_3.csv", index = False)

Other important thing to deal with in specimen information is Specimen date, though is not written in implementation docx file but it carry weight to model to determin the season of when the specimen was collected.

So here is to standardize the date on how to write them in this dataset, though thwy came with time in raw data but the time is same all which is 0000hrs but we got to remove the time and remain with dates only and standardize on how to write those dates in their column.

In [31]:
#contniue with recent cleaned csv file
sp_sd = pd.read_csv('specimen_information_clean_3.csv')

In [32]:
sp_sd['Specimen date'].sample(10, random_state=42)

1614    18/12/2024 12:00:00 AM
4121           2024-10-10 0:00
2677            2024-8-10 0:00
4213             2024-5-3 0:00
3194     28/7/2024 12:00:00 AM
561             2024-9-10 0:00
3765            2024-10-8 0:00
2187     22/3/2024 12:00:00 AM
1485    18/11/2024 12:00:00 AM
177             2024-5-12 0:00
Name: Specimen date, dtype: str

In [33]:
sp_sd['Specimen date'].unique()

<StringArray>
[         '2024-5-4 0:00',          '2024-2-6 0:00', '31/10/2024 12:00:00 AM',
  '18/8/2024 12:00:00 AM', '14/10/2024 12:00:00 AM', '24/10/2024 12:00:00 AM',
          '2024-4-1 0:00',          '2024-3-1 0:00',  '16/1/2024 12:00:00 AM',
  '18/1/2024 12:00:00 AM',
 ...
         '2024-12-9 0:00',  '13/7/2024 12:00:00 AM', '17/11/2024 12:00:00 AM',
 '21/12/2024 12:00:00 AM', '27/12/2024 12:00:00 AM', '29/12/2023 12:00:00 AM',
  '20/1/2024 12:00:00 AM',          '1959-6-2 0:00', '26/12/2024 12:00:00 AM',
          '2025-2-5 0:00']
Length: 373, dtype: str

In [34]:
sp_sd['Specimen date'].isnull().sum()

np.int64(2)

In [35]:
sp_sd['Specimen date'].dtype

- Standardize Specimen date
- Original data contained mixed date formats (DD/MM/YYYY and YYYY-M-D)
- Converted to datetime, then formatted as DD/MM/YYYY according to the research team's standard.

In [36]:
#Convert the data type in this column to be same standrd but in mixed formart
sp_sd['Specimen date'] = pd.to_datetime(
    sp_sd['Specimen date'], dayfirst= True, format= 'mixed'
    )

In [37]:
#verify
sp_sd['Specimen date'].dtype

dtype('<M8[us]')

In [38]:
sp_sd['Specimen date'].unique()

<DatetimeArray>
['2024-04-05 00:00:00', '2024-06-02 00:00:00', '2024-10-31 00:00:00',
 '2024-08-18 00:00:00', '2024-10-14 00:00:00', '2024-10-24 00:00:00',
 '2024-01-04 00:00:00', '2024-01-03 00:00:00', '2024-01-16 00:00:00',
 '2024-01-18 00:00:00',
 ...
 '2024-09-12 00:00:00', '2024-07-13 00:00:00', '2024-11-17 00:00:00',
 '2024-12-21 00:00:00', '2024-12-27 00:00:00', '2023-12-29 00:00:00',
 '2024-01-20 00:00:00', '1959-02-06 00:00:00', '2024-12-26 00:00:00',
 '2025-05-02 00:00:00']
Length: 373, dtype: datetime64[us]

In [39]:
sp_sd['Specimen date'].sample(10, random_state=42)

1614   2024-12-18
4121   2024-10-10
2677   2024-10-08
4213   2024-03-05
3194   2024-07-28
561    2024-10-09
3765   2024-08-10
2187   2024-03-22
1485   2024-11-18
177    2024-12-05
Name: Specimen date, dtype: datetime64[us]

In [40]:
#change date to team standard and remove time
sp_sd['Specimen date'] = sp_sd['Specimen date'].dt.strftime('%d/%m/%Y')

In [41]:
sp_sd['Specimen date'].sample(10, random_state=42)

1614    18/12/2024
4121    10/10/2024
2677    08/10/2024
4213    05/03/2024
3194    28/07/2024
561     09/10/2024
3765    10/08/2024
2187    22/03/2024
1485    18/11/2024
177     05/12/2024
Name: Specimen date, dtype: str

In [42]:
sp_sd['Specimen date'].unique()

<StringArray>
['05/04/2024', '02/06/2024', '31/10/2024', '18/08/2024', '14/10/2024',
 '24/10/2024', '04/01/2024', '03/01/2024', '16/01/2024', '18/01/2024',
 ...
 '12/09/2024', '13/07/2024', '17/11/2024', '21/12/2024', '27/12/2024',
 '29/12/2023', '20/01/2024', '06/02/1959', '26/12/2024', '02/05/2025']
Length: 373, dtype: str

In [43]:
#sp_sd.to_csv("specimen_information_clean_4.csv", index = False)

In [44]:
sp_sd['Specimen date'].head(20)

0     05/04/2024
1     02/06/2024
2     31/10/2024
3     18/08/2024
4     14/10/2024
5     24/10/2024
6     04/01/2024
7     03/01/2024
8     16/01/2024
9     18/01/2024
10    03/02/2024
11    11/02/2024
12    11/02/2024
13    08/02/2024
14    15/03/2024
15    23/03/2024
16    25/04/2024
17    23/05/2024
18    18/07/2024
19    27/07/2024
Name: Specimen date, dtype: str

In [45]:
sp_sd['Specimen date'].dtype

check if the date format problem is from panda or wps...

In [46]:
#check
sp_sd['Specimen date'].head(10)

0    05/04/2024
1    02/06/2024
2    31/10/2024
3    18/08/2024
4    14/10/2024
5    24/10/2024
6    04/01/2024
7    03/01/2024
8    16/01/2024
9    18/01/2024
Name: Specimen date, dtype: str

In [47]:
sp_sd['Specimen date'].dtype

there is an issue here. i see there some rows are in format of 2024-10-09 and other are in 15/03/2024 in specimen dates

In [48]:
#know which rows are still in the wrong format.
sp_sd[
    sp_sd['Specimen date'].str.contains('-', na=False)
]['Specimen date']

Series([], Name: Specimen date, dtype: str)

In [49]:
sp_sd['Specimen date'].str.contains('-', na=False).sum()

np.int64(0)

In [50]:
sp_sd.iloc[0:20][['Specimen date']]

   Specimen date
0     05/04/2024
1     02/06/2024
2     31/10/2024
3     18/08/2024
4     14/10/2024
5     24/10/2024
6     04/01/2024
7     03/01/2024
8     16/01/2024
9     18/01/2024
10    03/02/2024
11    11/02/2024
12    11/02/2024
13    08/02/2024
14    15/03/2024
15    23/03/2024
16    25/04/2024
17    23/05/2024
18    18/07/2024
19    27/07/2024

In [51]:
sp_sd['Specimen date'].value_counts().head(20)

Specimen date
12/03/2024    31
18/09/2024    29
09/10/2024    28
11/06/2024    28
02/08/2024    27
26/08/2024    27
10/05/2024    26
10/10/2024    26
14/03/2024    26
11/07/2024    26
08/10/2024    26
30/08/2024    25
05/08/2024    25
06/09/2024    25
06/04/2024    25
05/11/2024    25
11/01/2024    25
07/02/2024    25
18/01/2024    24
15/03/2024    24
Name: count, dtype: int64

In [52]:
check = pd.read_csv("specimen_information_clean_4.csv")

In [53]:
check['Specimen date'].head(10)

0    2024-05-04
1    2024-02-06
2    31/10/2024
3    18/08/2024
4    14/10/2024
5    24/10/2024
6    2024-04-01
7    2024-03-01
8    16/01/2024
9    18/01/2024
Name: Specimen date, dtype: str

In [54]:
check['Specimen date'].dtype